apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: generic
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: none

---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: hiperf
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
  replication-type: none
