apiVersion: v1
kind: PersistentVolume
metadata:
  name: wp-volume
  labels:
    app: wordpress
spec:
  storageClassName: generic
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: my-wp-disk
    fsType: ext4
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wp-pv-claim
  labels:
    app: wordpress
spec:
  storageClassName: generic
  accessModes:
    - ReadWriteOnce
  volumeName: wp-volume
  resources:
    requests:
      storage: 5Gi
---
